sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t raigen/rpi-alpine-nginx .
# test image
- docker run raigen/rpi-alpine-nginx nginx -v
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV NGINX_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag raigen/rpi-alpine-nginx raigen/rpi-alpine-nginx:$TAG
    docker push raigen/rpi-alpine-nginx:$TAG
    docker push raigen/rpi-alpine-nginx
  fi
